server:
  port: 8761
spring:
  application:
    name: flashcard-discovery-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    # stop Eureka from expiring instances when no heartbeat is received (true by default)
  