DROP TABLE BEAR;
DROP TABLE BEAR_TYPE;
DROP TABLE CAVE;
DROP TABLE BEEHIVE;
DROP TABLE BEAR_BEEHIVE;
--SCRIPTS OFTEN BEGIN WITH DROP STATEMENTS TO ENSURE NO NAMING CLASHES

--TABLE CREATION WITH PRIMARY KEYS

CREATE TABLE BEAR (
    BEAR_ID INTEGER PRIMARY KEY, --ADDING PK TO THIS COLUMN
    BEAR_NAME VARCHAR2(100),
    BIRTHDATE DATE,
    WEIGHT NUMBER(6,2) DEFAULT 200.00,
    BEAR_TYPE_ID INTEGER NOT NULL, --THIS WILL BE A NON-NULLABLE FOREIGN KEY
    CAVE_ID INTEGER --THIS WILL BE A NULLABLE FOREIGN KEY
);
/
CREATE TABLE BEAR_TYPE (
    BEAR_TYPE_ID INTEGER PRIMARY KEY,
    BEAR_TYPE_NAME VARCHAR2(100)
);
/
CREATE TABLE CAVE (
    CAVE_ID INTEGER PRIMARY KEY,
    CAVE_NAME VARCHAR2(100),
    MAX_BEARS INTEGER DEFAULT 4
);
/
CREATE TABLE BEEHIVE (
    BEEHIVE_ID INTEGER PRIMARY KEY,
    LBS_HONEY NUMBER(5,2) DEFAULT 75.00
);
/
CREATE TABLE BEAR_BEEHIVE (
    BEAR_ID INTEGER,
    BEEHIVE_ID INTEGER,
    PRIMARY KEY (BEAR_ID, BEEHIVE_ID)
);
/

--FOREIGN KEY CONSTRAINTS

--CONSTRAINT: RULE PLACED ON THE CONTENTS OF A TABLE, LIMITS WHAT MAY BE INSERTED
--TYPES - PK, FK, UNIQUE, CHECK, NOT NULL

ALTER TABLE BEAR
ADD CONSTRAINT FK_BEAR_BEAR_TYPE
FOREIGN KEY (BEAR_TYPE_ID) REFERENCES BEAR_TYPE(BEAR_TYPE_ID);
/

ALTER TABLE BEAR
ADD CONSTRAINT FK_BEAR_CAVE
FOREIGN KEY (CAVE_ID) REFERENCES CAVE(CAVE_ID);
/

ALTER TABLE BEAR_BEEHIVE
ADD CONSTRAINT FK_BEAR_BEAR_BEEHIVE
FOREIGN KEY (BEAR_ID) REFERENCES BEAR(BEAR_ID);
/

ALTER TABLE BEAR_BEEHIVE
ADD CONSTRAINT FK_BEEHIVE_BEAR_BEEHIVE
FOREIGN KEY (BEEHIVE_ID) REFERENCES BEEHIVE(BEEHIVE_ID);
/

--ADD SOME DATA
--TWO DIFFERENT FORMATS FOR INSERTING DATA: 
--FILL ALL COLUMNS OR ONLY A SELECT FEW. 

INSERT INTO CAVE VALUES (27, 'Tampa', 8);
INSERT INTO CAVE (CAVE_ID, CAVE_NAME) VALUES (53, 'Grand Rapids');

UPDATE CAVE SET CAVE_NAME = 'Tampa' WHERE CAVE_NAME = 'Denver';

INSERT ALL
INTO BEAR_TYPE
VALUES (34, 'Grizzly')
INTO BEAR_TYPE
VALUES (35, 'Sun')
SELECT * FROM DUAL; -- DUAL IS A DUMMY TABLE 

INSERT ALL
INTO BEAR
VALUES (1, 'Barry', TO_DATE('1993-10-08', 'yyyy-mm-dd'), 350.00, 34, 53)
INTO BEAR (BEAR_ID, BEAR_NAME, BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
VALUES (2, 'Berneice', TO_DATE('1993-10-08', 'yyyy-mm-dd'), 34, 53)
INTO BEAR (BEAR_ID, BEAR_NAME, BIRTHDATE, BEAR_TYPE_ID, CAVE_ID)
VALUES (3, 'Ben', TO_DATE('1980-04-28', 'yyyy-mm-dd'), 35, 27)
SELECT * FROM DUAL;



